spring:
  mail:
#    host: imap.gmail.com
    host: smtp.gmail.com
    username: gameShopContactMail
    password: rqapzljcxguzyasz
#    password: gameShopContactMail2000
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true